name: CI

on:
  pull_request:
    branches: [ develop, main ]  # PR 만들 때 자동 실행
  push:
    branches: [ develop ]
  workflow_dispatch: {}

jobs:
  unit-headless:
    name: unit (headless) - jdk${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [17, 21]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Run tests (headless)
        run: ./gradlew --no-daemon test
        env:
          JAVA_TOOL_OPTIONS: -Djava.awt.headless=true

